### ISSUE TITLE
[BUG] Error log using `meta list` command in server console.

### ISSUE THREAD

**Issue by crashzk** [ManifestManah/MetaCommandsBlocker#2]
Whenever I type the `meta list` command in the server console I receive this error log:
```
[39;49m[40m[39;49m[36m[40mSystem.NullReferenceException: Object reference not set to an instance of an object.

at MetaCommandsBlocker.MetaCommandsBlocker.CommandListener_BlockOutput(CCSPlayerController player, CommandInfo info) in C:\Users\Christoffer\Desktop\CSSharp\MetaCommandsBlocker\MetaCommandsBlocker.cs:line 54

[39;49m[39;49m[40m[39;49m[36m[40mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

---> System.NullReferenceException: Object reference not set to an instance of an object.

at MetaCommandsBlocker.MetaCommandsBlocker.CommandListener_BlockOutput(CCSPlayerController player, CommandInfo info) in C:\Users\Christoffer\Desktop\CSSharp\MetaCommandsBlocker\MetaCommandsBlocker.cs:line 54

at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass36_0.<AddCommandListener>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 245

at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

--- End of inner exception stack trace ---

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

[39;49m[39;49m[37m19:29:10[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m

[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m

[39;49m[37m ---> System.NullReferenceException: Object reference not set to an instance of an object.[39;49m

[39;49m[37m   at MetaCommandsBlocker.MetaCommandsBlocker.CommandListener_BlockOutput(CCSPlayerController player, CommandInfo info) in C:\Users\Christoffer\Desktop\CSSharp\MetaCommandsBlocker\MetaCommandsBlocker.cs:line 54[39;49m

[39;49m[37m   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass36_0.<AddCommandListener>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 245[39;49m

[39;49m[37m   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)[39;49m

[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m

[39;49m[37m   --- End of inner exception stack trace ---[39;49m

[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m

[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m

[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m

[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82[39;49m
```

**Comment by ManifestManah** [comment]
This error was caused as a result of a certain version of the CounterStrikeSharp having some problems. On newer versions than the  version you were using at the time, this problem was no longer there. So if you haven't already, then update your CounterStrikeSharp and the problem should be solved. Update it to the most recent version, or at least version 96, I know that the version 96 works without any issues as the new version of the plugin was tested and confirmed to be working using version 96.
